### ISSUE TITLE
Need help on anything?

### ISSUE THREAD

**Issue by ThomasVille** [Uriopass/Scale#2]
@Uriopass Hi, I started using Rust a few months ago and I'm looking for an interesting project like yours to work on.

I'm really interested in human society simulations so if you need help with anything right now, I would be pleased to help.

**Comment by Uriopass** [comment]
Hi ! 
I am very open to help, although for the moment the project is still in its beginning so everything is being reworked constantly.  
I don't really have a lot of things that are working, I'm mostly experimenting with different frameworks and libraries and ways to model things with Rust.  
If you want you can add me on Discord so that we can talk, my tag is Uriopass#(2*995 - 2).
I also suggest you join the unofficial discord server at https://discord.gg/7wKQKgc as its a cool place for rust development. 

You might also be interested by [Citybound](https://aeplay.org/citybound) and [abstreet](https://github.com/dabreegster/abstreet) which are a bit more fleshed out.

**Comment by Uriopass** [comment]
@ThomasVille

**Comment by ThomasVille** [comment]
Thank you for showing me Citybound and abstreet, these are two really interesting projects too!
I'll look more closely into Citybound as it looks more like a real society simulation though.
Also, this discord server is really cool!
